// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UprqOFNR2x66bHWL7NvAr_jJbKwtYeQ',
    appId: '1:1096894998638:web:2107a54db0a45fd1491e7f',
    messagingSenderId: '1096894998638',
    projectId: 'gps-attendance-app-cf827',
    authDomain: 'gps-attendance-app-cf827.firebaseapp.com',
    storageBucket: 'gps-attendance-app-cf827.firebasestorage.app',
    measurementId: 'G-R72GX7J2ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQw2s_2a75_VvywyY6nTYjp2fJh4_iiQ',
    appId: '1:1096894998638:android:e3b318ade07c0684491e7f',
    messagingSenderId: '1096894998638',
    projectId: 'gps-attendance-app-cf827',
    storageBucket: 'gps-attendance-app-cf827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5RW7McBZcideRFOls7AwVrxAlwK6LUp4',
    appId: '1:1096894998638:ios:faa1032053095004491e7f',
    messagingSenderId: '1096894998638',
    projectId: 'gps-attendance-app-cf827',
    storageBucket: 'gps-attendance-app-cf827.firebasestorage.app',
    iosBundleId: 'com.example.gpsAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5RW7McBZcideRFOls7AwVrxAlwK6LUp4',
    appId: '1:1096894998638:ios:faa1032053095004491e7f',
    messagingSenderId: '1096894998638',
    projectId: 'gps-attendance-app-cf827',
    storageBucket: 'gps-attendance-app-cf827.firebasestorage.app',
    iosBundleId: 'com.example.gpsAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6UprqOFNR2x66bHWL7NvAr_jJbKwtYeQ',
    appId: '1:1096894998638:web:2f5bfeec7a48c983491e7f',
    messagingSenderId: '1096894998638',
    projectId: 'gps-attendance-app-cf827',
    authDomain: 'gps-attendance-app-cf827.firebaseapp.com',
    storageBucket: 'gps-attendance-app-cf827.firebasestorage.app',
    measurementId: 'G-5P4ZCRWDKR',
  );
}
